# Generated by Django 2.1.5 on 2019-02-24 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_control_pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_anios', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contrato',
            name='periodos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_control_pagos.Periodo'),
        ),
    ]
