# Generated by Django 2.1.5 on 2019-02-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control_pagos', '0002_auto_20190224_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='prima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
