# Generated by Django 2.1.5 on 2019-02-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_control_pagos', '0003_contrato_prima'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePlanPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('cuota_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cuota_intereses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amortizacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_pago', models.DateField()),
                ('cuota_pagada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('abono', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('saldo_deuda', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('meses', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='tasa',
            field=models.TextField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='planpagos',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_control_pagos.Contrato'),
        ),
        migrations.AddField(
            model_name='detalleplanpagos',
            name='plan_pagos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_control_pagos.PlanPagos'),
        ),
    ]
