# Generated by Django 2.1.5 on 2019-02-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control_pagos', '0004_auto_20190224_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleplanpagos',
            old_name='fecha_pago',
            new_name='fecha_maxima_pago',
        ),
    ]
