# Generated by Django 2.1.5 on 2019-02-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control_pagos', '0005_auto_20190224_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tasa',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
