# Generated by Django 2.1.5 on 2019-02-24 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_control_pagos', '0007_auto_20190224_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='periodos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_control_pagos.Periodo'),
        ),
    ]
