# Generated by Django 2.1.5 on 2019-03-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control_pagos', '0009_contrato_tipo_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_venta',
            field=models.CharField(blank=True, choices=[('credito', 'Crédito'), ('contado', 'Contado')], max_length=7, null=True),
        ),
    ]
