# Generated by Django 2.1.5 on 2019-03-02 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_control_pagos', '0010_auto_20190302_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono 1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono 2'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_adquisicion',
            field=models.DateTimeField(verbose_name='Fecha adquisición'),
        ),
    ]
