# Generated by Django 2.1.5 on 2019-03-02 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_control_pagos', '0011_auto_20190302_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpagos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
