# Generated by Django 2.1.5 on 2019-03-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control_pagos', '0012_planpagos_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
