# Generated by Django 3.2 on 2025-09-12 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_control_pagos', '0017_auto_20250909_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplanpagos',
            name='abono_registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleplanpagos',
            name='fecha_abono_capital',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
