# Generated by Django 3.2 on 2025-09-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control_pagos', '0018_auto_20250912_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre', 'apellido']},
        ),
    ]
